FROM node:18-alpine

WORKDIR /azure-trial
COPY . .

WORKDIR /azure-trial/secretBatchRetrievalConnector

RUN npm install 

RUN npm update && \
    npm i -g tfx-cli

WORKDIR /azure-trial

CMD ["tfx", "extension", "create", "--manifest-globs", "vss-extension.json"]