"use strict";
exports.__esModule = true;
var tmrm = require("azure-pipelines-task-lib/mock-run");
var path = require("path");
var taskPath = path.join(__dirname, '..', 'index.js');
var tmr = new tmrm.TaskMockRunner(taskPath);
var endpointId = "ConjurService";
tmr.setInput(endpointId, endpointId);
process.env['ENDPOINT_URL_' + endpointId] = "http://localhost";
process.env["ENDPOINT_DATA_" + endpointId + "_" + 'conjuraccount'.toUpperCase()] = 'myConjurAccount';
process.env["ENDPOINT_DATA_" + endpointId + "_" + 'conjurusername'.toUpperCase()] = 'host/BotApp/myDemoApp';
process.env["ENDPOINT_DATA_" + endpointId + "_" + 'conjurapikey'.toUpperCase()] = '3ded3pp1x1w3ak3ter2kj22532mx2xfk51z2p28p';
tmr.setInput('secretsyml', path.join(__dirname, '..', 'test/test-secrets.yml'));
tmr.run();
